import pyautogui
import time

scroll_amount = 2
wait_time = 0.1

pyautogui.alert('não use até finalizar')
time.sleep(1)
for _ in range(1):
    pyautogui.click(x = 646, y = 60)
    pyautogui.write('clima')
    pyautogui.press('enter')
    time.sleep(5)
    pyautogui.click(x = 646, y = 60)
    pyautogui.hotkey('ctrl','a')
    pyautogui.press('backspace')
    pyautogui.write('tubarão')
    pyautogui.press('enter')
    time.sleep(5)
    pyautogui.click(x = 646, y = 60)
    pyautogui.hotkey('ctrl','a')
    pyautogui.press('backspace')
    pyautogui.write('shampoo')
    pyautogui.press('enter')
    time.sleep(5)
    pyautogui.click(x = 646, y = 60)
    pyautogui.hotkey('ctrl','a')
    pyautogui.press('backspace')
    pyautogui.write('variáveis')
    pyautogui.press('enter')
    time.sleep(5)
    pyautogui.click(x = 646, y = 60)
    pyautogui.hotkey('ctrl','a')
    pyautogui.press('backspace')
    pyautogui.write('besteria')
    pyautogui.press('enter')
    time.sleep(5)
    pyautogui.click(x = 646, y = 60)
    pyautogui.hotkey('ctrl','a')
    pyautogui.press('backspace')
    pyautogui.write('bateria de lítio')
    pyautogui.press('enter')
    time.sleep(5)
    pyautogui.click(x = 646, y = 60)
    pyautogui.hotkey('ctrl','a')
    pyautogui.press('backspace')
    pyautogui.write('wolksvagem')
    pyautogui.press('enter')
pyautogui.alert('fim')